### ISSUE TITLE
Generate function in new codebase

### ISSUE THREAD

**Issue by kshitijkg** [AGI-Collective/multimodal#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Proposed solution**
If you have an idea for how we can fix this problem, describe it here.

**Screenshots**

**Environment (please complete the following information):**
 - GPUs:
- Configs:

**Additional context**

**Comment by floatingbigcat** [comment]
https://github.com/AGI-Collective/multimodal/pull/43
